# Generated by Django 6.1.1 on 2026-09-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('last_heartbeat', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('reported_status', models.CharField(blank=True, max_length=32)),
                ('metrics', models.JSONField(default=dict)),
            ],
        ),
    ]
